version: '3'
services:

  authorization-server:
    build: .
    container_name: authorization-server
    ports:
     - "8080:8080"
    depends_on:
      - authorization-server-db
  authorization-server-db:
    container_name: authorization-server-db
    image: postgres:10.4
    ports:
     - "5432:5432"